config/routes.rb
Rails.application.routes.draw do
  get 'hello/hello'

  get 'hello/world'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def hello
  end

  def world
    @time = Time.now
    @files = Dir.glob('*')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/views/hello/hello.html.erb
<h1>Hello#hello</h1>
<p>Find me in app/views/hello/hello.html.erb</p>
<p><%= link_to "ワールド", hello_world_path %></p>

app/views/hello/world.html.erb
<h1>Hello! My First Rails Application!</h1>
<p>Find me in app/views/hello/world.html.erb</p>
<p><%= @time %></p>
<p><%= link_to "もどる", hello_hello_path %></p>
<h4>足し算</h4>
<p><%= 100 + 10 %></p>
<h4>文字列連結</h4>
<p><%= "hoge" + "fuga" %></p>
<h4>1h後の時間</h4>
<p><%= 1.hour.from_now %></p>
<h4>ディレクトリ配下のファイル一覧</h4>
<% for file in @files %>
  <ul>ファイル名：<%= file %></ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyFirstRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>